"""L.RB-12.7: Slice B's fossil band names real producers (the states themselves are generated by
L.J-SLICE-B.1, CM-5, not here: running the producers takes seconds per state and is the leaf
verifier's `fossils generate` step over a scratch copy)."""

from __future__ import annotations

import importlib
import sys
from pathlib import Path

from tests.proof import fossils
from tests.proof.b import fossil_states

ROOT = Path(__file__).resolve().parents[3]
BAND = "slice-b"  # named for its checkpoint: d2 awaits J-SLICE-B for a band with no directories yet
STATES = {
    "b-inflight-reference_env_postgres_wait": "interrupted",
    "b-terminal-reference_env": "succeeded",
    "b-views-reference_env": "succeeded",
}


def test_manifest_names_every_b_state_with_a_resolvable_producer() -> None:
    states = fossils.load_states()  # a state id declared in two MANIFESTs is a load error (MC-11)
    mine = {sid: entry for sid, (band, entry) in states.items() if band == BAND}
    assert set(mine) == set(STATES)
    for sid, entry in sorted(mine.items()):
        assert sid.startswith("b-")
        assert entry["absent"] is False and entry["producer"] != "pending"
        module, function = str(entry["producer"]).split(":")
        assert module == "tests.proof.b.fossil_states"
        assert callable(getattr(importlib.import_module(module), function)), sid
        assert entry["s0_projection"]["state"] == STATES[sid]  # type: ignore[index]


def test_the_seam_spellings_are_the_twins() -> None:
    """The generator's process cannot import the env tests' `twin` package, so it spells the seams;
    the plugin processes import them, and these are the twins' own constants."""
    sys.path.insert(0, str(ROOT / "packages" / "trestle-env" / "tests"))
    try:
        from twin import fake_binding
    finally:
        sys.path.remove(str(ROOT / "packages" / "trestle-env" / "tests"))
    assert fossil_states.HEALTHY_SEAM == fake_binding.SEAM
    assert fossil_states.WRONG_PASSWORD_SEAM == fake_binding.WRONG_PASSWORD_SEAM
    assert fossil_states.PLUGIN.is_file()
