"""L.SL-11.2: the single-level fossil band's MANIFEST names real producers and the states E-SV3-1
speaks of; the states themselves are generated by L.J-SINGLE.1 (CM-5), not here (running every
producer takes tens of seconds and is the leaf verifier's PROC step)."""

from __future__ import annotations

import importlib
import json
import tomllib
from pathlib import Path

from tests.proof import fossils, harness

ROOT = Path(__file__).resolve().parents[3]
BAND = "single"
SINGLE_STATES = {
    "inflight-plan-bearing",
    "terminal-passed",
    "terminal-cancelled",
    "terminal-timed-out",
    "planless-started",
}
HOLD_LEAF = ROOT / "tests" / "fixtures" / "workflows" / "hold_leaf.py"


def test_manifest_names_every_single_state_with_a_resolvable_producer() -> None:
    states = fossils.load_states()  # a state id declared in two MANIFESTs is a load error
    mine = {sid for sid, (band, _) in states.items() if band == BAND}
    assert mine == SINGLE_STATES
    for sid in sorted(mine):
        _, entry = states[sid]
        assert entry["absent"] is False and entry["producer"] != "pending"
        module, function = str(entry["producer"]).split(":")
        assert callable(getattr(importlib.import_module(module), function)), sid
        assert entry["s0_projection"]["state"] in {  # type: ignore[index]
            "succeeded",
            "cancelled",
            "timed_out",
            "interrupted",
        }


def test_e_sv3_1_names_a_state_of_this_band() -> None:
    exceptions = tomllib.loads((ROOT / "tests" / "proof" / "d2_exceptions.toml").read_text())
    (e_sv3_1,) = [e for e in exceptions["exception"] if e["id"] == "E-SV3-1"]
    assert e_sv3_1["states"] == [f"{BAND}/inflight-plan-bearing"]
    assert "inflight-plan-bearing" in fossils.load_states()


def test_hold_leaf_is_admitted_plan_bearing() -> None:
    """The deadline producer's fixture admits as a declared one-vertex root (no run is driven)."""
    admitted = harness.admit_tree(HOLD_LEAF, {"env": "dev"})
    spec = json.loads((admitted.run_dir / "evidence" / "spec.json").read_text(encoding="utf-8"))
    assert isinstance(spec["plan"]["declaration_digest"], str)
